name: reader_rebuild_mobile
description: A rebuildable reader app client.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  flutter_cache_manager: ^3.4.1
  http: ^1.2.1
  just_audio: ^0.10.4
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.2.3
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
